{"name": "test_login_0_failed_by_wrong_datas[data2]", "uuid": "7b958afa-c2e8-45c8-9dda-038b8b544b19", "labels": [{"name": "tag", "value": "login"}, {"name": "subSuite", "value": "TestLoginP"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "host", "value": "G50-75M"}, {"name": "thread", "value": "13544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login_pytest"}], "historyId": "2ccd9b197d81af3dca9b411f49db3e45", "status": "passed", "stop": 1561894591319, "parameters": [{"name": "data", "value": "{'password': 'python', 'user': '186847205531', 'check': '请输入正确的手机号'}"}], "fullName": "TestCases.test_login_pytest.TestLoginP#test_login_0_failed_by_wrong_datas[data2]", "start": 1561894590640}