{"name": "test_login_0_failed_by_wrong_datas[data1]", "uuid": "b36ac605-dfb6-4cfd-80f0-c3860943bf34", "labels": [{"name": "tag", "value": "login"}, {"name": "subSuite", "value": "TestLoginP"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "host", "value": "G50-75M"}, {"name": "thread", "value": "13544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login_pytest"}], "historyId": "80d9377c0bc951243a83d4fa54c0b331", "status": "passed", "stop": 1561894589903, "parameters": [{"name": "data", "value": "{'password': '', 'user': '18684720553', 'check': '请输入密码'}"}], "fullName": "TestCases.test_login_pytest.TestLoginP#test_login_0_failed_by_wrong_datas[data1]", "start": 1561894589183}