{"name": "test_login_1_failed_by_fail_datas[data1]", "uuid": "8e0f3f61-4a4c-49b1-97d1-3ae12442e9b5", "labels": [{"name": "tag", "value": "login"}, {"name": "subSuite", "value": "TestLoginP"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "host", "value": "G50-75M"}, {"name": "thread", "value": "13544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login_pytest"}], "historyId": "db41b1a355a03c0075c72827e7d9bf96", "status": "passed", "stop": 1561894599523, "parameters": [{"name": "data", "value": "{'password': '123456', 'user': '18684720553', 'check': '帐号或密码错误!'}"}], "fullName": "TestCases.test_login_pytest.TestLoginP#test_login_1_failed_by_fail_datas[data1]", "start": 1561894598249}