{"name": "test_login_0_failed_by_wrong_datas[data0]", "uuid": "db05edc8-d899-4eff-a048-924da0681fdc", "labels": [{"name": "tag", "value": "login"}, {"name": "subSuite", "value": "TestLoginP"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "host", "value": "G50-75M"}, {"name": "thread", "value": "13544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login_pytest"}], "historyId": "4de02333fd275499480d05dbee234dc2", "status": "passed", "stop": 1561894588388, "parameters": [{"name": "data", "value": "{'password': 'python', 'user': '', 'check': '请输入手机号'}"}], "fullName": "TestCases.test_login_pytest.TestLoginP#test_login_0_failed_by_wrong_datas[data0]", "start": 1561894587374}